source "$HOME/.zsh/aliases.zsh"
source "$HOME/.zsh/completion.zsh"
source "$HOME/.zsh/general.zsh"
source "$HOME/.zsh/history.zsh"
source "$HOME/.zsh/hooks.zsh"
source "$HOME/.zsh/keymap.zsh"
source "$HOME/.zsh/spaceship.zsh"
source "$HOME/.zsh/zinit.zsh"
