source "$HOME/.zsh/general.zsh"
source "$HOME/.zsh/history.zsh"
source "$HOME/.zsh/completions.zsh"
source "$HOME/.zsh/hooks.zsh"
source "$HOME/.zsh/zinit.zsh"
source "$HOME/.zsh/aliases.zsh"
source "$HOME/.zsh/keymaps.zsh"

[[ $(uname -s) == "Darwin" ]] && source "$HOME/.zsh/homebrew.zsh"
[[ $(uname -s) == "Linux" ]] && source "$HOME/.zsh/yay.zsh"
