column_limit: 80
indent_width: 2
continuation_indent_width: 2
keep_simple_control_block_one_line: false
keep_simple_function_one_line: false
align_args: false
# break_after_functioncall_lp: true
# break_before_functioncall_rp: true
# break_after_functiondef_lp: true
# break_before_functiondef_lp: true
chop_down_parameter: true
chop_down_table: true
single_quote_to_double_quote: true
