[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "easymotion/vim-easymotion"
hook_add = """
let g:EasyMotion_smartcase = 1

" move to char
map <Leader><CR> <Plug>(easymotion-bd-f)
nmap <Leader><CR> <Plug>(easymotion-overwin-f)

" move to line
map<Leader>g <Plug>(easymotion-bd-jk)
nmap <Leader>g <Plug>(easymotion-overwin-line)
"""

[[plugins]]
repo = "editorconfig/editorconfig-vim"

[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = """
let g:lightline = {
\   "colorscheme": "onedark",
\ }
"""

[[plugins]]
repo = "NovaDev94/lightline-onedark"
